### ISSUE TITLE
Add ksqlDB process active handler to run the pull query to against to KTable

### ISSUE THREAD

**Issue by GavinChenYan** [networknt/light-kafka#102]
Add ksqlDB process active handler to run the pull query to against to KTable

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add ksqlDB process active handler to run the pull query to against to KTable light-kafka master](https://trello.com/c/vq3v3PCR/1220-add-ksqldb-process-active-handler-to-run-the-pull-query-to-against-to-ktable-light-kafka-master)
