### ISSUE TITLE
Enable  idempotence for producer to support Transactional API

### ISSUE THREAD

**Issue by PeterKieu** [networknt/light-kafka#22]
This fully enables Kafka transactional API in term of exactly-once-processing:
Check KafkaProducerConfig.java with :
```
 private boolean enableIdempotence;
```
In TransactionalProducer.java ,  add 
```
producerProps.put("enable.idempotence", config.isEnableIdempotence());
```
In any Kafka-Transactional-based project  ./config/kafka-producer.yml  add this line:
```
 enable.idempotence: true
```

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enable idempotence for producer to support Transactional API light-kafka master](https://trello.com/c/YW0MVCwM/929-enable-idempotence-for-producer-to-support-transactional-api-light-kafka-master)
